version: 2.1
orbs:
  snyk: snyk/snyk@2.2.0
  python: circleci/python@3.3.0
jobs:
  build_test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: uv
      - snyk/scan
workflows:
  build_test_deploy:
    jobs:
      - build_test
