version: '2.1'
orbs:
  trivy: cci-labs/trivy:latest
jobs:
  trivy:
    docker:
      - image: cimg/base:2024.11
    environment:
      TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
    steps:
      - checkout
      - aqua-trivy/scan:
          format: sarif
          ignore-unfixed: true
          output: report.sarif
          scan-type: fs
workflows:
  demo:
    jobs:
      - trivy
