version: 2.1
orbs:
  snyk: snyk/snyk@2.2.0
  python: circleci/python@3.3.0
jobs:
  build_test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Update apt
          command: sudo apt-get update
      - run:
          name: Install system dependencies
          command: sudo apt-get install python3-dev
      - python/install-packages:
          pkg-manager: uv      
      - run:
          name: Export requirements
          command: >
            uv export 
            --quiet 
            --no-hashes 
            --format requirements.txt 
            --output-file requirements.txt 
            --no-emit-project 
            --no-annotate 
            --no-header
      - snyk/scan
workflows:
  build_test_deploy:
    jobs:
      - build_test
