version: '2.1'
orbs:
  trivy: cci-labs/trivy@1.0.0
jobs:
  trivy:
    docker:
      - image: cimg/base:edge
    environment:
      TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
    steps:
      - checkout
      - trivy/scan:
          format: sarif
          ignore-unfixed: true
          output: report.sarif
          scan-type: fs
workflows:
  trivy-scan:
    jobs:
      - trivy
