name: helpr
on:
  push:
  pull_request:
jobs:
  trunk:
    name: helpr
    runs-on: ubuntu-latest
    steps:
      - uses: AlphaSphereDotAI/helpr_action@main
        with:
          is_test: true
          lint: true
