name: helpr
on:
  push:
    branches: main
  pull_request:
jobs:
  helpr:
    name: helpr
    runs-on: ubuntu-latest
    steps:
      - uses: AlphaSphereDotAI/helpr_action@main
        with:
          is_test: true
          lint: true
          linter: pre-commit
          github_token: ${{ secrets.GH_TOKEN }}
