name: pyapp
on:
  push:
permissions: read-all
jobs:
  build_binary:
    name: Build Binary Distribution
    environment:
      name: pyapp
      url: https://github.com/${{github.repository}}/commits/${{github.ref_name}}
    runs-on: ubuntu-latest
    env:
      PYAPP_PROJECT_NAME: ${{ github.event.repository.name }}
      PYAPP_PROJECT_VERSION: "0.0.1"
      PYAPP_FULL_ISOLATION: "1"
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5        
      - uses: dtolnay/rust-toolchain@stable
      - name: Install uv
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          activate-environment: true
      - uses: robinraju/release-downloader@v1
        with:
          repository: ofek/pyapp
          latest: true
          extract: true
          tarBall: true
          out-file-path: pyapp
      - run: ls -alh
        working-directory: pyapp
      - run: mv ofek-pyapp-* pyapp-latest
        working-directory: pyapp
      - run: ls -alh pyapp-latest
        working-directory: pyapp
      - run: cargo build --release
        working-directory: pyapp/pyapp-latest
      - run: mv target/release/pyapp ${{ github.event.repository.name }}
        working-directory: pyapp/pyapp-latest
      - run: chmod +x ${{ github.event.repository.name }}
        working-directory: pyapp/pyapp-latest
      - name: Upload artifacts
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: dist
          path: pyapp/pyapp-latest/${{ github.event.repository.name }}
  github_release:
    name: Create GitHub Release
    needs: [build_binary]
    runs-on: ubuntu-latest
    environment:
      name: github
      url: ${{github.event.repository.html_url}}/releases/tag/${{github.ref_name}}
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Download artifacts
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
        with:
          name: dist
          path: dist/
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.4.2
        with:
          files: pyapp/pyapp-latest/*
