name: pyapp
on:
  push:
permissions: read-all
jobs:
  build_binary:
    name: Build Binary Distribution
    environment:
      name: pyapp
      url: https://github.com/${{github.repository}}/commits/${{github.ref_name}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5        
      - uses: dtolnay/rust-toolchain@stable
      - name: Install uv
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          activate-environment: true
      - uses: robinraju/release-downloader@v1
        with:
          repository: ofek/pyapp
          latest: true
          extract: true
          tarBall: true
      - run: ls -a
      - name: Build
        run: hatch build --target binary
      - run: ls -a dist/
      - run: cp dist/binary/* dist/
      - run: rm -rd dist/binary/
      - name: Upload artifacts
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: dist
          path: dist/
  github_release:
    name: Create GitHub Release
    needs: [build_binary]
    runs-on: ubuntu-latest
    environment:
      name: github
      url: https://github.com/${{github.repository}}/releases/tag/${{github.ref_name}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Download artifacts
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
        with:
          name: dist
          path: dist/
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: >-
          gh release create ${{ github.ref_name }} dist/* --title ${{ github.ref_name }} --generate-notes
