name: t1
on:
  push:
jobs:
  build_image:
    name: test
    runs-on: matrix.os
    strategy:
      matrix:
        os: [ubuntu-slim, ubuntu-latest]
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
