name: t1
on:
  push:
jobs:
  build_image:
    name: test
    runs-on: ubuntu-slim
    steps:
      # - name: Free Disk Space
      #   uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
      - uses: robinraju/release-downloader@v1
        with:
          fileName: '*' #'disease_assistant-*.whl disease_assistant-*.tar.gz'
          latest: true
      - run: ls -alh
